### PR TITLE
Add OSGi meta information

### PR DESCRIPTION
**Pull request by anton-johansson**

### CODE REVIEW

**Comment by FlavioF** [comment]
Thank you for your contribution

**Comment by anton-johansson** [comment]
You're welcome! We are messing around with this library as we are considering using it in our production code.

Speaking of which, this project is being maintained, correct? I just want to avoid using something that might die in the near future. :)

**Comment by FlavioF** [comment]
We are using it in Production.

**Comment by anton-johansson** [comment]
Good to know, thanks!

**Pull request merged**
